spring.application.name=emosdk

spring.datasource.url=jdbc:postgresql://localhost:5435/emosdk
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

narrative.assets.storage-dir=uploads/narrative-assets
narrative.assets.public-url-prefix=/narrative-assets
narrative.assets.max-size-bytes=10485760

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
